### PR TITLE
Added actual quest levels to use for tooltips.

### PR DESCRIPTION
**Pull request by ZoeyZolotova**
Updated the quest database with the addition of "questLevel" for each quest, which is the actual level of the quest, not the required level.
Removed/renamed/fixed some quests in the database.
Updated QuestieNotes to now have the available/complete quest tooltips show the questLevel instead of the minimum level.

### CODE REVIEW

**Comment by Schaka** [comment]
What's the point of having the quest level? The level it was showing is for when you can pick up the quest. Questlevels can sometimes be 40, even if you can pick up the quest at level 18.

**Comment by ZoeyZolotova** [comment]
Every other quest addon shows the quest level in square brackets, which makes it very confusing when Questie shows [18] but when you pick it up it says [40] and it seems like Questie is just wrong. It doesn't seem to me that the level you can pick up a quest is important information for a player. The only thing they really need to know is whether or not they can pick it up at all, and this change doesn't affect that since it still uses the min-level to determine when to show a quest on the map.

**Comment by Schaka** [comment]
Good point, I'll merge it.

**Comment by ZoeyZolotova** [comment]
Thanks! Mark #246 as fixed?

**Comment by ZoeyZolotova** [comment]
For the record, I used https://vanilla-twinhead.twinstar.cz/ as the source of my data, with a few exceptions that I hard-coded (for example all the Call of Water quests are level 20 even though twinhead says 2 of them are 60). Group quests are marked with a + (e.g. [40+]), dungeon quests with a D (e.g. [25D]), raid quests with an R, and pvp quests with PVP.

**Comment by Muehe** [comment]
Did you do anything about player level quests? No idea how twinhead lists them, but they would have level -1 in the DB.

**Comment by ZoeyZolotova** [comment]
I was not aware of anything like that, so no.

**Comment by Muehe** [comment]
Did a quick lookup, shouldn't be much of a problem:

```
mysql> SELECT entry FROM mangos.quest_template WHERE QuestLevel = -1;
+-------+
| entry |
+-------+
|  9029 |
|  9367 |
|  9368 |
+-------+

```

**Pull request merged**
