### PR TITLE
hideUnexploredMapIcons option

### PR DESCRIPTION
**Pull request by soldovskij**
I will add hideUnexploredMapIcons option, to hide icons on unexplored area

### CODE REVIEW

**Comment by soldovskij** [comment]
it is realization

**Comment by AeroScripts** [comment]
Hey thanks for your work! I'll look in to this shortly, looks good though

Been busy the past couple days

**Comment by soldovskij** [comment]
May be right hide icons only map and stay on mini map?

**Comment by AeroScripts** [comment]
Sorry for delaying this still, 4.1.1 is going to be a bugfix update(there are some problems).

Should be ok to merge after today's release. Thanks again for your work its a cool addition

**Comment by soldovskij** [comment]
Thank you!

**Comment by soldovskij** [comment]
@AeroScripts Hi! 
How are you doing with the bug fix?

**Comment by BreakBB** [comment]
@soldovskij Sorry for the late response. We totally forgot about this PR. Could you update it so we can merge it?

**Comment by soldovskij** [comment]
@BreakBB Yes, done =)

**Comment by soldovskij** [comment]
I'm not sure, maybe need subscribe on `WORLD_MAP_UPDATE` to refresh icons if chekbox enabled

**Comment by soldovskij** [comment]
@AeroScripts @BreakBB Hello, I updated. All ready to confirm.

**Comment by BreakBB** [comment]
You have to do some more. I just checkout this PR and I am greeted with an error message stating that "WORLD_MAP_UPDATE" is not a known event for Ace.

And indeed it is not listed at https://wow.gamepedia.com/Events/Classic

So you have to find another way for this and actually test it :)

**Comment by soldovskij** [comment]
Yes, right. Need MAP_EXPLORATION_UPDATED. Just a minute

**Comment by soldovskij** [comment]
@BreakBB In game test complete, work pretty :)

**Comment by soldovskij** [comment]
@BreakBB Hey! If you have free minute - merge it :)

**Comment by soldovskij** [comment]
@BreakBB Hey! I'm still here )

**Comment by BreakBB** [comment]
Sorry for taking so long @soldovskij Just tested it and it's looking good, thanks for this :)

**Pull request merged**
