### PR TITLE
Change tracker fonts

### PR DESCRIPTION
**Pull request by saenic**
- Added LibSharedMedia-3.0 and AceGUI-3.0-SharedMediaWidgets libraries
- Font change possibility added for header and lines
- Defaults to "Friz Quadrata TT" which is always available

tracker1

tracker2

### CODE REVIEW

**Comment by saenic** [comment]
I just saw the other tracker pull request https://github.com/AeroScripts/QuestieDev/pull/1910. I could wait with my PR until this one is merged and then add font chance option on top.

**Comment by Dyaxler** [comment]
LOL... this is awesome. I have a skin pack I used for PallyPower that uses LSM. I was thinking about adding it but the list of changes I did were getting a little long. I'll wait for this to get checked in then piggy back off yours and take advantage of LSM. :)

I like how you lined up the font drop downs with the third column from above.

**Comment by Dyaxler** [comment]
@saenic I think you forgot to include the changes you made to the localization strings into your commit.

I imported your PR into my fork and am testing it against my tracker changes and this is what I'm now seeing since the tags have changed and there are a couple missing.

image

**Comment by Dyaxler** [comment]
NM... I had to update all the language files in my fork anyway. Your new tags were fairly straight forward anyways. :)

**Comment by Dyaxler** [comment]
image

**Comment by saenic** [comment]
Closed because its its included in @Dyaxler 's Pull Request https://github.com/AeroScripts/QuestieDev/pull/1917

**Pull request closed without merging**
