### PR TITLE
Update config.lua

### PR DESCRIPTION
**Pull request by iron217**
I'm sorry when the conflict eliminated something I did wrong, I will no longer)

### CODE REVIEW

**Comment by BreakBB** [comment]
@iron217 don't worry! Again: You simply removed the last empty line in the file. We (currently) don't have strict rules for it!

**Comment by iron217** [comment]
there old errors got out which I already corrected

**Comment by iron217** [comment]
please make a merge so that I already sleep peacefully

**Comment by BreakBB** [comment]
Hey @iron217 Sorry for not being fast enough on this PR! We're just a few people and it's not easy to test/check everything really fast.

We would be happy if you keep PRing things to Questie 👍 Your translations and previous PRs have been really good and helpful! We sometimes just need some time to get to it.

**Pull request closed without merging**
