### PR TITLE
Fixes 2 pats for Quest Givers

### PR DESCRIPTION
**Pull request by Gogo1951**
# Morin Cloudstalker
	- pats Mulgore
	https://classic.wowhead.com/npc=2988/morin-cloudstalker
	[215]{51.4,59.2}{59.6,62.4}

# Gann Stonespire
	- pats The Barrens
	https://classic.wowhead.com/npc=3341/gann-stonespire
	[17]{46.0,75.4}{46.0,81.2}

### CODE REVIEW

**Comment by Gogo1951** [comment]
Hey @Muehe, please merge these when you get a chance. Thanks!

**Comment by BreakBB** [comment]
@Gogo1951 what was wrong with those waypoints? I thought they were shown correctly :thinking:

Also if you add just two locations it will be a straight line between them which is not always ideal imo.

**Comment by Gogo1951** [comment]
The problem with both of these NPCs is that while the DB does have a lot of patrol points listed, neither of these NPCs show up as having a patrol path in-game.

When I add the new points, they show up correctly.

If you have any insight as to why the coordinates in the DB don't work I'd be keen on learning; I just put the end points of the pat, seems accurate enough when I tested it -- they both walk in straight lines up and down their respective roads.

`[2988] = {'Morin Cloudstalker',198,198,10,10,0,{[215]={{57.2,61.22},},},{[17]={{34.68,58.94},{34.85,58.99},{35.08,59.1},{35.24,59.19},{35.4,59.28},{35.56,59.37},{35.73,59.46},{35.89,59.55},{36.05,59.63},{36.21,59.72},{36.38,59.81},{36.6,59.93},{36.81,60.02},{37.03,60.06},{37.42,60.04},{37.52,60.03},{37.73,59.99},{38.1,59.84},{38.43,59.68},{38.53,59.63},{38.86,59.49},{39.03,59.42},{39.19,59.35},{39.34,59.29},{39.53,59.18},{39.68,59.07},{39.84,58.96},{39.99,58.85},{40.17,58.75},{40.45,58.65},{40.7,58.59},{40.87,58.58},{40.6,58.58},{40.38,58.65},{40.26,58.69},{39.91,58.87},{39.7,59.03},{39.61,59.1},{39.38,59.25},{39.18,59.34},{39.01,59.41},{38.84,59.48},{38.68,59.55},{38.51,59.63},{38.35,59.7},{38.18,59.77},{38.02,59.84},{37.85,59.91},{37.62,60.01},{37.41,60.06},{37.19,60.08},{37.02,60.05},{36.79,60.01},{36.6,59.94},{36.44,59.85},{36.28,59.75},{36.12,59.65},{35.96,59.55},{35.8,59.46},{35.38,59.23},{35.28,59.17},{35.12,59.09},{34.87,58.98},{34.7,58.93},{34.52,58.88},{34.35,58.86},{34.16,58.84},{33.96,58.78},{33.75,58.67},{33.53,58.6},{33.31,58.55},{33.03,58.55},{32.81,58.53},{32.59,58.46},{32.26,58.29},{32.05,58.18},{31.95,58.08},{32.16,58.24},{32.36,58.37},{32.54,58.45},{32.64,58.49},{32.87,58.54},{33.04,58.56},{33.21,58.58},{33.38,58.6},{33.57,58.63},{33.78,58.69},{34.0,58.81},{34.23,58.88},{34.54,58.9},},[215]={{57.2,61.22},{57.55,61.32},{57.99,61.54},{58.31,61.72},{58.64,61.89},{58.96,62.06},{59.28,62.24},{59.6,62.41},{59.92,62.59},{60.24,62.76},{60.56,62.93},{60.99,63.17},{61.42,63.34},{61.84,63.43},{62.62,63.39},{62.82,63.37},{63.22,63.3},{63.97,63.0},{64.61,62.68},{64.81,62.59},{65.46,62.31},{65.79,62.16},{66.12,62.02},{66.4,61.9},{66.77,61.69},{67.08,61.47},{67.39,61.25},{67.68,61.04},{68.04,60.85},{68.58,60.64},{69.08,60.52},{69.42,60.51},{68.89,60.5},{68.45,60.64},{68.22,60.72},{67.52,61.09},{67.11,61.4},{66.93,61.54},{66.47,61.83},{66.08,62.0},{65.75,62.14},{65.43,62.28},{65.1,62.43},{64.77,62.57},{64.44,62.71},{64.12,62.85},{63.79,63.0},{63.46,63.14},{63.02,63.33},{62.59,63.44},{62.16,63.46},{61.82,63.41},{61.37,63.33},{61.01,63.2},{60.69,63.0},{60.37,62.81},{60.06,62.62},{59.74,62.43},{59.43,62.24},{58.6,61.79},{58.39,61.67},{58.07,61.52},{57.59,61.29},{57.26,61.2},{56.89,61.1},{56.55,61.06},{56.18,61.02},{55.79,60.91},{55.37,60.69},{54.94,60.54},{54.51,60.45},{53.97,60.45},{53.53,60.4},{53.09,60.28},{52.45,59.94},{52.03,59.72},{51.82,59.51},{52.25,59.83},{52.63,60.09},{53.0,60.25},{53.2,60.33},{53.63,60.44},{53.97,60.47},{54.31,60.51},{54.65,60.55},{55.02,60.6},{55.43,60.73},{55.88,60.97},{56.32,61.09},{56.94,61.13},},[357]={{91.12,0.06},{91.37,0.14},{91.7,0.3},{91.94,0.43},{92.17,0.56},{92.41,0.69},{92.65,0.82},{92.88,0.95},{93.12,1.08},{93.36,1.2},{93.6,1.33},{93.91,1.51},{94.23,1.63},{94.55,1.7},{95.12,1.67},{95.26,1.66},{95.56,1.6},{96.12,1.38},{96.59,1.15},{96.74,1.08},{97.22,0.87},{97.46,0.76},{97.7,0.66},{97.91,0.57},{98.19,0.41},{98.42,0.25},{98.64,0.09},{98.44,0.2},{98.31,0.3},{97.97,0.51},{97.68,0.64},{97.44,0.75},{97.19,0.85},{96.95,0.96},{96.71,1.06},{96.47,1.17},{96.23,1.27},{95.99,1.38},{95.74,1.49},{95.41,1.63},{95.1,1.7},{94.78,1.72},{94.53,1.68},{94.2,1.62},{93.93,1.53},{93.69,1.38},{93.46,1.24},{93.23,1.1},{92.99,0.96},{92.76,0.82},{92.15,0.49},{92.0,0.4},{91.76,0.28},{91.4,0.12},{91.16,0.05},{90.92,0.0},},[15]={{0.11,10.44},{0.43,10.61},{0.74,10.78},{1.05,10.95},{1.37,11.12},{1.68,11.29},{2.1,11.52},{2.52,11.69},{2.94,11.77},{3.7,11.73},{3.89,11.72},{4.29,11.64},{5.02,11.36},{5.65,11.04},{5.84,10.95},{6.48,10.67},{6.8,10.53},{7.12,10.4},{7.39,10.28},{7.76,10.07},{8.06,9.85},{8.36,9.64},{8.65,9.44},{9.01,9.25},{9.54,9.05},{10.02,8.93},{10.36,8.91},{9.84,8.91},{9.4,9.04},{9.17,9.13},{8.49,9.48},{8.1,9.78},{7.92,9.92},{7.47,10.2},{7.08,10.37},{6.76,10.51},{6.44,10.65},{6.12,10.79},{5.8,10.93},{5.48,11.07},{5.16,11.21},{4.84,11.35},{4.52,11.49},{4.09,11.68},{3.67,11.78},{3.25,11.8},{2.92,11.75},{2.48,11.67},{2.12,11.54},{1.81,11.36},{1.5,11.17},{1.19,10.98},{0.88,10.79},{0.57,10.61},},},215,{749,764,765,},{751,764,765,},104,"H",nil,2,},`

`[3341]` = {'Gann Stonespire',417,417,18,18,0,{[17]={{45.89,77.0},},},{[15]={{20.05,44.53},{20.05,44.53},{20.15,44.16},{20.36,43.54},{20.38,43.37},{20.42,42.57},{20.43,42.17},{20.46,41.81},{20.54,41.33},{20.54,41.33},{20.45,41.94},{20.44,42.34},{20.43,42.74},{20.4,43.29},{20.32,43.73},{20.07,44.38},{19.95,44.94},{19.87,46.03},{19.88,46.83},{19.91,47.38},{19.99,47.88},{20.19,48.31},{20.35,48.64},{20.51,49.05},{20.55,49.44},{20.5,50.19},{20.47,50.58},{20.46,50.98},{20.48,51.78},{20.49,52.18},{20.48,52.58},{20.47,52.98},{20.49,53.38},{20.47,54.18},{20.44,54.86},{20.45,55.26},{20.47,55.66},{20.49,56.46},{20.49,56.86},{20.48,57.26},{20.39,58.35},{20.21,58.71},{20.05,59.03},{19.75,59.69},{19.63,59.87},{19.78,59.54},{20.11,58.91},{20.34,58.45},{20.45,57.98},{20.48,57.23},{20.48,56.62},{20.48,56.22},{20.46,55.42},{20.45,55.04},{20.47,54.64},{20.51,53.88},{20.5,53.48},{20.49,53.08},{20.48,52.28},{20.48,52.28},{20.47,51.3},{20.47,50.9},{20.49,50.5},{20.53,49.65},{20.53,49.25},{20.41,48.69},{20.26,48.36},{20.1,48.04},{19.91,47.58},{19.86,46.71},{19.86,46.31},{19.87,45.36},{19.92,44.89},},[17]={{45.89,77.03},{45.89,77.03},{45.94,76.84},{46.05,76.52},{46.07,76.43},{46.08,76.01},{46.09,75.81},{46.11,75.62},{46.14,75.37},{46.14,75.37},{46.1,75.69},{46.1,75.89},{46.09,76.1},{46.07,76.39},{46.03,76.62},{45.9,76.95},{45.84,77.24},{45.8,77.81},{45.8,78.22},{45.82,78.51},{45.86,78.76},{45.97,78.99},{46.05,79.16},{46.13,79.37},{46.15,79.57},{46.13,79.96},{46.11,80.17},{46.1,80.37},{46.12,80.79},{46.12,80.99},{46.12,81.2},{46.11,81.41},{46.12,81.62},{46.11,82.03},{46.09,82.38},{46.1,82.59},{46.11,82.8},{46.12,83.21},{46.12,83.42},{46.12,83.62},{46.07,84.19},{45.98,84.38},{45.9,84.54},{45.74,84.88},{45.68,84.98},{45.75,84.8},{45.93,84.48},{46.04,84.24},{46.1,84.0},{46.12,83.61},{46.12,83.29},{46.12,83.09},{46.1,82.67},{46.1,82.48},{46.11,82.27},{46.13,81.88},{46.13,81.67},{46.12,81.46},{46.12,81.05},{46.12,81.05},{46.11,80.54},{46.11,80.33},{46.12,80.13},{46.14,79.69},{46.14,79.48},{46.08,79.19},{46.0,79.02},{45.92,78.85},{45.82,78.61},{45.79,78.16},{45.79,77.95},{45.8,77.46},{45.83,77.22},},[215]={{79.33,96.9},{79.33,96.9},{79.43,96.52},{79.65,95.89},{79.67,95.71},{79.7,94.9},{79.72,94.49},{79.75,94.12},{79.82,93.64},{79.82,93.64},{79.74,94.26},{79.73,94.66},{79.72,95.07},{79.69,95.64},{79.6,96.09},{79.35,96.75},{79.22,97.32},{79.15,98.43},{79.15,99.25},{79.18,99.81},{79.13,99.13},{79.13,98.73},{79.15,97.75},{79.2,97.27},},[400]={{36.72,0.03},{36.74,0.5},{36.76,1.46},{36.76,1.93},{36.75,2.41},{36.65,3.71},{36.43,4.14},{36.24,4.52},{35.88,5.31},{35.74,5.52},{35.91,5.13},{36.31,4.38},{36.58,3.83},{36.71,3.27},{36.75,2.38},{36.75,1.65},{36.74,1.17},{36.72,0.22},},},17,{843,846,849,},{843,846,849,},104,"H",nil,3,},`

**Comment by Gogo1951** [comment]
image

Had a friend snap that.

**Comment by Gogo1951** [comment]
So I guess it does pat... weird, because when I ran it... no pat shown. Oof. Let me re-test. Have to get another toon to South Barrens. Kill me.

**Comment by BreakBB** [comment]
@Gogo1951 I am not sure about this, but I think if an NPC has waypoints for multiple zones only one of them is drawn.

This is actually a good behaviour but effects some database entries which need to be "cleaned" from the waypoints they're not really patrolling in.

We don't want to show quests/markers from other areas.

**Pull request closed without merging**
