### PR TITLE
Incomplete quest objectives becomes yellow

### PR DESCRIPTION
**Pull request by Yemto**
Incomplete quest objectives becomes yellow, which makes them easier to see, especially when playing in groups.

### CODE REVIEW

**Comment by BreakBB** [comment]
@Yemto Thanks for this PR! I am not sure what exactly you changed so it would be great if you could share a screenshot to show the changes!

**Comment by Yemto** [comment]
It makes it so incomplete quest objectives in the tooltip, minimap and map becomes yellow, while completed ones are green. To make it easier to see when playing in a group. But it also applies when playing solo.
Skärmklipp 2019-10-31 18 31 41
Skärmklipp 2019-10-31 18 31 14

**Comment by Yemto** [comment]
Skärmklipp 2019-11-03 (2)
Skärmklipp 2019-11-03 (1)
Skärmklipp 2019-11-03

**Comment by BreakBB** [comment]
@Yemto If you have a look at the tracker and it's options you will find a dropdown for coloring the objectives with multiple variations. E.g. from red to green.

I think it would be the best if you adapt that code to make the tooltips work the same way.

If you need help with anything or have questions feel always free to ask here or on Discord! We're happy for every help and PR we ger :smiley:

**Comment by Yemto** [comment]
The tooltip now follows the objectives coloring option and added "white and green", which makes it so completed objectives are green, otherwise they are white. But I'm not sure I got the colors right, and since I don't know any other languages than english, I made all Locale says "white and green"

**Comment by Yemto** [comment]
Skärmklipp 2019-11-07
Skärmklipp 2019-11-07 (1)
Skärmklipp 2019-11-07 (3)

**Comment by BreakBB** [comment]
@Yemto Thanks for updating this. I just had a short look at the files you changed and would like you to fix the indentation of some files. I will have a more detailed look after that :+1:

**Comment by BreakBB** [comment]
Thank you very, very much for this great PR 🎉

**Pull request merged**
