### PR TITLE
Update locales.

### PR DESCRIPTION
**Pull request by EKE00372**

### CODE REVIEW

**Comment by AeroScripts** [comment]
thanks for the translations <3

**Comment by AeroScripts** [comment]
Can you review this and remove the change to enUS config.lua? JOURNEY_NOTE_CREATED is a used string

**Comment by EKE00372** [comment]
they are same?

['JOURNEY_NOTE_CREATED'] = "Note Created: %s",
['JOURNEY_NOTE_CREATED'] = "Your Created a new Note titled: %s",

**Comment by AeroScripts** [comment]
Oh my bad, just saw the commit and didnt know it was a duplicate, thanks again!

**Pull request merged**
