### PR TITLE
[quest] Correctly mark "Message to the Wildhammer" chain as Normal quests

### PR DESCRIPTION
**Pull request by drejjmit**
No PvP involved. Icons doesn't show for people with PvP icons disabled.
#2182

### CODE REVIEW

**Comment by BreakBB** [comment]
@drejjmit Well the quest is marked as PvP by Blizzard so we shouldn't unmark it as such, should we? Also this doesn't fix the issue from what I see

**Comment by drejjmit** [comment]
I spoke to Gogo in PM about this and he couldn't see any objectives of these quests (7841,7842 and 7843). Then i saw the PvP tag and he got them showing by enable PvP icons. 
image

These tree and ``The Last Barov (5344, 5342) are the only quests outside Battlegrounds that are tagged PvP:
https://classic.wowhead.com/quests/type:41

I don't see a reason for them to be PvP tagged and include them in PvP filtering since they don't involve any PvP.

**Comment by BreakBB** [comment]
Hmmm... I think we shouldn't filter objectives at all. When a quest is in your quest log then the objectives for those should show. Don't you think that will be the better solution?

**Comment by drejjmit** [comment]
This fix requires no coding ^^ And it will still hide the available icon for these three + barov quests if you fix it like that.

**Comment by BreakBB** [comment]
Alright, alright. For now you win 😛

**Pull request merged**
