### PR TITLE
[WIP] Add possible fix for #653

### PR DESCRIPTION
**Pull request by BreakBB**
The "exclusiveTo" field already had the quests for once guiding to the same trainer, but missing the ones at a different capital. This PRs adds all available quests for one faction onto each quest.

I wasn't sure if only the missing IDs should be added or all of them.

### CODE REVIEW

**Comment by Muehe** [comment]
Not sure if this should be fixed with adding the quests as exclusive or by changing the race requirements of the quest, but I suspect it's the latter. We need to check if the quests from other capitals are available until the one in the own capital is finished, or if they are never available in the first place.

**Comment by BreakBB** [comment]
Right now we can't do much on this since not even the Wowhead data is correct where you can accept which quest. I suspect Blizzard changed things on Classic for these quests

**Comment by Muehe** [comment]
Most of the mangos/wowhead data is from TBC times, and it's possible they made class quests available to other races only after Classic as a QOL change for people leveling together. We could level a hunter and check...

**Comment by Muehe** [comment]
Ok, so I have a Orc hunter on level 10 now, he isn't able to accept quests for the Tauren pet quest, but one NPC in Thunderbluff offers a breadcrumb quest which isn't shown by Questie:


Screenshot_20191008_180438

**Comment by BreakBB** [comment]
Closing since it is obsolete.

**Pull request closed without merging**
