### PR TITLE
[quest] Fixes for Breaking the Keystone

### PR DESCRIPTION
**Pull request by Gogo1951**
Giving Fozruk a pat.

* Breaking the Keystone - Quest - World of Warcraft || https://classic.wowhead.com/quest=652/breaking-the-keystone
* Rod of Order - Item - World of Warcraft || https://classic.wowhead.com/item=4469/rod-of-order
* Fozruk - NPC - World of Warcraft || https://classic.wowhead.com/npc=2611/fozruk

### CODE REVIEW

**Comment by Gogo1951** [comment]
Fozruk has a pretty large pat, and to simplify it I rounded the spawn points by 2. In my test seems accurate enough and still shows where all to look for him.

**Comment by BreakBB** [comment]
@Gogo1951 Could you share a screenshot of the changes you did here?

**Comment by drejjmit** [comment]
image

**Comment by BreakBB** [comment]
First of all there I can not see clear waypoints with this commit. Just streamlining the coords and removing some won't fix the underlying problem and is neither a bandaid. Maybe you can check #2186 and add spawns like this @Gogo1951 . Fozruk has a clear path he is walking.

**Pull request closed without merging**
